steps:
- name: 'ubuntu'
  args: ["echo", '"{\"tag\":\"${TAG_NAME}\",\"branch\":\"${BRANCH_NAME}\",\"commit\":\"${SHORT_SHA}\"}"', ">", "./server/gitinfo.json"]

- name: 'ubuntu'
  args: ["ls", "./server"]

  - name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=$_DOCKER_USER_ID --password=$$PASSWORD"]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'ecosis/ecosml-webapp:$BRANCH_NAME', './server']

images: ['ecosis/ecosml-webapp:$BRANCH_NAME']

secrets:
  - kmsKeyName: "projects/$PROJECT_ID/locations/global/keyRings/ci/cryptoKeys/ecosisdev-dockerhub"
  secretEnv:
    PASSWORD: "$_DOCKER_USER_PASSWORD"