steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'echo "{\"tag\":\"${TAG_NAME}\",\"branch\":\"${BRANCH_NAME}\",\"commit\":\"${SHORT_SHA}\"}" > ./server/gitinfo.json']

- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', "ls ./server"]

- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', "pwd"]

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=ecosisdev-dockerhub-password > pass.txt' ]

- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=$_DOCKER_USER_ID --password-stdin < pass.txt"]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'ecosis/ecosml-webapp:$BRANCH_NAME', './server']

images: ['ecosis/ecosml-webapp:$BRANCH_NAME']