steps:
- name: 'ubuntu'
  args: ['echo', "{\"tag\":\"${TAG_NAME}\",\"branch\":\"${BRANCH_NAME}\",\"commit\":\"${SHORT_SHA}\"}", ">", "./server/gitinfo.json"]

- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=$_DOCKER_USER_ID --password=\"$_DOCKER_USER_PASSWORD\""]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'ecosis/ecosml-webapp:$BRANCH_NAME', 'server/']

images: ['ecosis/ecosml-webapp:$BRANCH_NAME']