version: '2'

services:

  server:
    build: ../../server
    volumes:
      - git-data:/server/gitdata
      - ../secrets.json:/server/secrets.json
    ports:
      - 3001:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ECOSIS_HOST=${ECOSIS_HOST}
      - SERVER_ASSET_DIR=dist
      - GITHUB_ORG=ecosml-dev

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:3.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  git-data:
  redis-data: