version: '2'

services:

  server:
    image: ecosis/ecosml-webapp:dev
    volumes:
      - git-data:/server/gitdata
      - ../google-key.json:/server/google-key.json
      - ../secrets.js:/server/secrets.js
      - storage:/storage
    ports:
      - 3001:3000
    env_file: '.env'
    environment:
      - CLIENT_ENV=prod
      - SERVER_ENV=dev
      - GITHUB_ORG=ecosml-dev
      - FIREBASE_ENV=dev

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:3.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  git-data:
  redis-data:
  snapshot-data:
  storage: