version: '2'

services:

  server:
    build: ../../server
    volumes:
      - git-data:/server/gitdata
      - ../secrets.json:/server/secrets.json
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_ASSET_DIR=dist
      - GITHUB_ORG=ecosml

  redis:
    image: redis:3.2

  mongo:
    image: mongo:3.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  git-data: