version: '2'

services:

  server:
    image: ecosis/ecosml-webapp:prod
    volumes:
      - git-data:/server/gitdata
      - ../google-key.json:/server/google-key.json
      - ../secrets.js:/server/secrets.js
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ECOSIS_HOST=${ECOSIS_HOST}
      - CLIENT_ENV=prod
      - SERVER_ENV=prod
      - GITHUB_ORG=ecosml
      - FIREBASE_ENV=prod

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:3.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  git-data:
  redis-data: