version: '2'

services:

  server:
    image: ecosis/ecosml-webapp:master
    volumes:
      - snapshot-data:/server/snapshots
      - git-data:/server/gitdata
      - ../google-key.json:/server/google-key.json
      - ../secrets.js:/server/secrets.js
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ECOSIS_HOST=${ECOSIS_HOST}
      - CLIENT_ENV=prod
      - SERVER_ENV=prod
      - GITHUB_ORG=ecosml
      - FIREBASE_ENV=prod
      - SERVER_URL=${SERVER_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:3.5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  git-data:
  redis-data:
  snapshot-data: