version: '2'

services:

  server:
    image: node:8.7
    volumes:
      - ../../server:/app
      - ../secrets.json:/app/secrets.json
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_HOST=mongo
    command: tail -f /dev/null

  redis:
    image: redis:3.2

  mongo:
    image: mongo:3.5
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: