version: '2'

services:

  server:
    image: ecosis/ecosml-webapp:dev
    volumes:
      - ../../server/controllers:/server/controllers
      - ../../server/dist:/server/dist
      - ../../server/gitdata:/server/gitdata
      - ../../server/lib:/server/lib
      - ../../server/models:/server/models
      - ../../server/public:/server/public
      - ../../server/templates:/server/templates
      - ../../server/tests:/server/tests
      - ../../server/uploads:/server/uploads
      - ../../server/index.js:/server/index.js
      - ../google-key.json:/server/google-key.json
      - ../secrets.js:/server/secrets.js
      - storage:/storage
    ports:
      - 3000:3000
      - 9229:9229
    env_file: '.env'
    environment:
      - GITHUB_ORG=ecosml-dev
      - FIREBASE_ENV=dev
    command: tail -f /dev/null

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  mongo:
    image: mongo:3.5
    # ports:
    #   - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  redis-data:
  snapshot-data:
  storage: