version: '2'

services:

  server:
    image: node:8.7
    volumes:
      - ../../server:/app
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
    command: tail -f /dev/null

  redis:
    image: redis:3.2